id: 1148307481085358190
name: Dev Server
roles:
  - name: Moderator
    id: 1148307481391542288
  - name: ATC
    id: 1148307481227964444
  - name: Giveaway
    id: 1148307481227964436
ratings-roles:
  - name: S1
    rating-value: 2
    id: 1148307481152454744
  - name: S2
    rating-value: 3
    id: 1148307481152454745
  - name: S3
    rating-value: 4
    id: 1148307481173434538
  - name: C1
    rating-value: 5
    id: 1148307481173434539
  - name: C3
    rating-value: 7
    id: 1148307481173434540
  - name: I1
    rating-value: 8
    id: 1148307481173434541
  - name: I3
    rating-value: 10
    id: 1148307481173434542
  - name: SUP
    rating-value: 11
    id: 1148307481152454736
  - name: ADM
    rating-value: 12
    id: 1148307481085358199
pilot-rating-roles:
  - name: P0
    rating-value: 0
    id: 1148307481152454737
  - name: P1
    rating-value: 1
    id: 1148307481152454738
  - name: P2
    rating-value: 3
    id: 1148307481152454739
  - name: P3
    rating-value: 7
    id: 1148307481152454740
  - name: P4
    rating-value: 15
    id: 1148307481152454741
  - name: P5
    rating-value: 31
    id: 1148307481152454742
  - name: P6
    rating-value: 63
    id: 1148307481152454743
channels:
  - name: Git Channel
    id: 1148307485904601172
  - name: Screenshot Contest
    id: 1148307483002155098
  - name: Crew Chat
    id: 1148307482557554763
emojis:
  - name: TPC Reaction
    id: :giveaway:1225560451279097926
baseurl:
  - name: FCP
    url: https://flightcrew-beta.thepilotclub.org
  - name: Internal API
    url: https://api-beta.thepilotclub.org
  - name: Leaderboard
    url: https://mee6.xyz/thepilotclub
role_rewards:
  - role_name: Frequent Flyer
    role_id: 1148307481290866804
    level: 2
  - role_name: Commuter
    role_id: 1148307481290866803
    level: 1
  - role_name: VIP
    role_id: 1148307481290866805
    level: 3
xp_channels:
  - name: crew-chat
  - name: fly-with-me
  - name: Event Comms
  - name: Flight Voice 1
  - name: Flight Voice 2
  - name: Shared Cockpit
  - name: Magneto Lounge
  - name: 1 on 1
  - name: general-aviation-ops
  - name: streams-and-videos
  - name: screenshots
  - name: Charters Comms
  - name: community-help-forum
  - name: pilot-training-chat
  - name: charters-chat
  - name: explorer-missions
  - name: irl-pilots
  - name: atc-lounge
  - name: company-perks
  - name: early-adopters
  - name: airliner-and-bizjet-ops
  - name: rotary-ops
  - name: your-setups
